name: 'evvy_dbt'
version: '1.0.0'
profile: 'evvy_dbt'  # Ensure this is set and matches profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

